name: CD for NestJS Deployment

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SERVER_USER:
        required: true
      SERVER_HOST:
        required: true
      SERVER_PORT:
        required: true
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true
      SLACK_WEBHOOK_URL:
          required: true
    inputs:
      APP_NAME:
        required: true
        type: string
      APP_PATH:
        required: true
        type: string
      NODE_ENV:
        required: true
        type: string

jobs:
  deploy:
    permissions:
      contents: read
      actions: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: altairharbor.duckdns.org
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      
      - name: Build and push
        env:
          APP_NAME: ${{ inputs.APP_NAME }}
          NODE_ENV: ${{ inputs.NODE_ENV }}
        run: |
          docker buildx build \
            --push \
            -t altairharbor.duckdns.org/diarity-web-fe/${APP_NAME}:${NODE_ENV} \
            --build-arg ENVIRONMENT=${NODE_ENV} \
            .

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export APP_NAME=${{ inputs.APP_NAME }}
            export NODE_ENV=${{ inputs.NODE_ENV }}
            export APP_PATH=${{ inputs.APP_PATH }}
            docker login altairharbor.duckdns.org -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
            docker pull altairharbor.duckdns.org/$APP_NAME/$APP_NAME:$NODE_ENV
            docker stop $APP_NAME || true
            docker rm $APP_NAME || true
            docker run -d \
              --name $APP_NAME \
              --restart always
              -p 3000:3000 \
              -v $APP_PATH/logs:/usr/src/app/logs \
              altairharbor.duckdns.org/$APP_NAME/$APP_NAME:$NODE_ENV
            docker image prune -f
          
      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}